[package]
name = "monitor_diretorio_v2"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "5.0"
mysql = "26.0.0"
chrono = "0.4"
tray-icon = "0.20"
winit = "0.29"

# para windows
[profile.release]
lto = true

